
name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
      - uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USER_NAME}}
          passwork: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}