
name: Published Docker hub

on:
  push:
    branches:
      - master
      - dev

jobs:
  production:
    environment: Production
    name: Deploy Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/prod:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/prod:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/prod:buildcache,mode=max

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/dev' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          context: ./
          file: ./Dockerfile.dev
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/dev:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/dev:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/dev:buildcache,mode=max
