
name: Published Docker hub

on:
  push:
    branches: [ master ]

jobs:
  production:
    environment: Production
    name: Deploy Production
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/react-ci-cd
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/react-ci-cd:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/react-ci-cd:buildcache,mode=max