
name: React CI

on:
  push:
    branches: [ master ]

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Test Docker images
      run: |
        # Enable experimental features of Docker Daemon to run multi-arch
        # images.
        echo "$(cat /etc/docker/daemon.json)" '{"experimental": true}' \
        | jq --slurp 'reduce .[] as $item ({}; . * $item)' \
        | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        make npm.install
        make test.docker platforms=@all build=yes
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache image
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys:
            ${{ runner.os }}-buildx-

      - name: Build and push docker image to dockerhub
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: react-cd:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildxcache

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}